### PR TITLE
The big clean up

### PR DESCRIPTION
**Pull request by diasdavid**
> WIP

### CODE REVIEW

**Comment by diasdavid** [comment]
**Let scrutiny begin**

@richardlitt @noffle @dignifiedquire can you CR the code please? 

After finishing here, I'll bring https://github.com/diasdavid/registry-static to be part of the project instead of a dependency that gets run as a shell command, so that I can get more interesting stats and control of what it is doing.

**Comment by diasdavid** [comment]
There is a note on the README important to be able to run the tests https://github.com/diasdavid/registry-mirror/tree/refactor/the-big-clean-up#development

**Comment by dignifiedquire** [comment]
Will check!

**Comment by RichardLitt** [comment]
I don't understand; what does this PR do?

**Comment by dignifiedquire** [comment]
@diasdavid left some preliminary comments. Also travis is unhappy

**Comment by noffle** [comment]
@diasdavid: could we get some more context? What are the high-level goals of this refactor?

**Comment by diasdavid** [comment]
@dignifiedquire thank you for the CR, I've pushed changes following you comments :)

@RichardLitt @noffle Apologies for not being clear, this PR is the transformation of registry-mirror from a collection of hacks and glue to it all work to a more structured code base, where there is order, making contribution and debugging easier

**Comment by diasdavid** [comment]
@dignifiedquire travis is unhappy due to the missing 0.4.0 binary :)

**Comment by diasdavid** [comment]
Will move ahead and merge this one, to be able to go to the next step, merge registry-static into the mix :)

**Pull request merged**
